
import React from 'react';
import { motion } from 'framer-motion';
import { X, Bot, Lightbulb, MessageSquare } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface AIResponseBoxProps {
  question: string;
  response: string;
  type?: 'general' | 'wrong_answer' | 'quiz_help';
  context?: any;
  onClose: () => void;
}

const AIResponseBox: React.FC<AIResponseBoxProps> = ({ 
  question, 
  response, 
  type = 'general',
  context,
  onClose 
}) => {
  const getIcon = () => {
    switch (type) {
      case 'wrong_answer':
        return <Lightbulb className="w-5 h-5 text-orange-600" />;
      case 'quiz_help':
        return <Bot className="w-5 h-5 text-blue-600" />;
      default:
        return <MessageSquare className="w-5 h-5 text-blue-600" />;
    }
  };

  const getTitle = () => {
    switch (type) {
      case 'wrong_answer':
        return 'AI Explanation';
      case 'quiz_help':
        return 'AI Study Assistant';
      default:
        return 'AI Assistant';
    }
  };

  const getBadgeColor = () => {
    switch (type) {
      case 'wrong_answer':
        return 'bg-orange-100 text-orange-800';
      case 'quiz_help':
        return 'bg-green-100 text-green-800';
      default:
        return 'bg-blue-100 text-blue-800';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="fixed top-20 right-6 z-50 max-w-md w-full"
    >
      <Card className="backdrop-blur-md bg-white/95 border-white/20 shadow-xl">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-lg">
              {getIcon()}
              {getTitle()}
            </CardTitle>
            <div className="flex items-center gap-2">
              <Badge className={getBadgeColor()}>
                {type === 'wrong_answer' ? 'Learning' : type === 'quiz_help' ? 'Study Help' : 'General'}
              </Badge>
              <Button
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="h-8 w-8 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-3">
          {type === 'wrong_answer' && context?.topic && (
            <div className="text-xs text-gray-500 bg-gray-50 px-2 py-1 rounded">
              Topic: {context.topic}
            </div>
          )}
          
          <div>
            <h4 className="font-medium text-gray-800 mb-1 text-sm">
              {type === 'wrong_answer' ? 'Question:' : 'Your Question:'}
            </h4>
            <p className="text-gray-600 text-sm bg-blue-50 p-2 rounded">
              {question.length > 100 ? question.substring(0, 100) + '...' : question}
            </p>
          </div>
          
          <div>
            <h4 className="font-medium text-gray-800 mb-1 text-sm">
              {type === 'wrong_answer' ? 'AI Explanation:' : 'AI Response:'}
            </h4>
            <div className="text-gray-700 text-sm bg-gray-50 p-3 rounded max-h-60 overflow-y-auto">
              <pre className="whitespace-pre-wrap font-sans">{response}</pre>
            </div>
          </div>
          
          {type === 'wrong_answer' && (
            <div className="text-xs text-orange-600 bg-orange-50 p-2 rounded">
              💡 This explanation was generated by AI to help you learn from your mistake.
            </div>
          )}
        </CardContent>
      </Card>
    </motion.div>
  );
};

export default AIResponseBox;
